config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show, :edit]
  resources :orders, only: [:new, :edit]
  resources :coins, only: :edit

  root 'products#index'

end

app/models/product.rb
require_relative 'concerns/actions.rb'
class Product < ApplicationRecord
  validates_presence_of :name, :price
  has_attached_file :product_image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\z/

  extend Actions::ProductClass
  include Actions::ProductInstance

end

app/controllers/products_controller.rb
#I used Ruby because it's the language I'm most comfortable in, but after doing this project, I'm not sure Rails was the best framework to use. I probably should have just done a CLI, but by the time I realized this, it was too late because I had already done so much work on the front end. Rails favors convention over configuration. This particular project had a lot of custom logic that probably would have been a better fit for a framework like Node.js that favors configuration over convention.
class ProductsController < ApplicationController
  def index
    current_order #associates session with instance of order
    @products = Product.all
    @coins = Coin.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    params["id"] == ":id" ? @product = Product.product_selected? : @product = Product.find(params[:id])
    @product.selected == false ? @product.select_button : @product.deselect_button
    redirect_to root_path
  end
end

app/views/products/index.erb
<div class="row justify-content-md-left">
  <div class="col-sm-12 col-md-4">
    <div class="card">
      <div class="card-block">
        <table class="table table-hover">
          <tbody>
            <tr>
              <td><%=current_order.user_message(Product.product_selected?)%></td>
            </tr>
            <tr>
              <td><%=current_order.coin_return(Product.product_selected?)%></td>
            </tr>
          </tbody>
        </table>
        <%= button_to "Return Coins", edit_order_path(current_order), :class=> "btn btn-primary", :method => :get %>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-8">
    <li>Click on a coin to insert it.</li>
    <li>Click on a product to select it. If you've changed your mind, click on the product again, and you'll be able to see the rest of the products again.</li>
    <li>If you have made a successful purchase, or if the product you wish to purchase is sold out, please wait a few seconds for a page redirect.</li>
    <li>Machine always starts off with zero quarters, zero nickels, and zero dimes, and will not guarantee change unless a user has made a successful purchase with one of each.</li>
    <li>Note: program is supposed to restore bottom pictures of coins at the end of each round. I purposely designed the program this way for the sake of being able to make a purchase as many times as desired.</li>
  </div>
  </div>

<div class="container">
  <div class="row">
    <% if @products.all? {|product| product.selected == false } %>
    <% @products.each {|product| %>
      <div class="col-sm-12 col-md-4">
        <div class="text-center card" style="width: 7rem;">
          <%=link_to image_tag(product.product_image.url(:med)), edit_product_path(product)%>
          <div class="card-block">
            <p class="card-text"><%= product.name %></p>
            <p class="card-text">$<%= '%.2f' % product.price %></p>
          </div>
        </div>
     </div>
    <%}%>
    <%elsif Product.product_selected?%>
      <div class="col-sm-12 col-md-4">
        <div class="text-center card" style="width: 7rem;">
          <%=link_to image_tag(Product.product_selected?.product_image.url(:med)), edit_product_path(Product.product_selected?)%>
          <div class="card-block">
            <p class="card-text"><%= Product.product_selected?.name %></p>
            <p class="card-text">$<%= '%.2f' % Product.product_selected?.price %></p>
          </div>
        </div>
     </div>
    <%end%>
  </div>

  <div class="row">
    <% @coins.each {|coin| %>
      <div class="col-md-2">
        <%if Coin.all_valid_coins.include?(coin)%>
          <%= link_to(image_tag(coin.coin_image, :class => "coin-hidden"), edit_coin_path(coin)) %>
        <%else%>
          <%= link_to(image_tag(coin.coin_image, :class => "coin"), edit_coin_path(coin)) %>
        <%end%>
      </div>
    <%}%>
  </div>
</div>